service:
  type: NodePort

extraPorts:
  - name: "otelgrpc"
    port: 4317
    targetPort: 4317
    protocol: "TCP"
  - name: "otelhttp"
    port: 4318
    targetPort: 4318
    protocol: "TCP"
  
alloy:
  configMap:
    create: true
    content: |
      livedebugging {
        enabled = true
      }

      logging {
        level  = "info"
        format = "logfmt"
      }

      prometheus.scrape "kubernetes" {
        targets = [ "localhost:9100" ]
      }

      prometheus.remote_write "grafana_cloud" {
        endpoint {
          url = "https://prometheus-prod-49-prod-ap-northeast-0.grafana.net/api/prom/push"
          basic_auth {
            username = "3bb7fee6-2639-477a-bb67-644ede60bdac"
            password = "<API Key>"
          }
        }
        external_labels = {
          cluster = "minikube",
        }
      }

      loki.source.kubernetes "pods" {}

      loki.write "grafana_cloud" {
        endpoint {
          url = "https://logs-prod-030.grafana.net/loki/api/v1/push"
          basic_auth {
            username = "3bb7fee6-2639-477a-bb67-644ede60bdac"
            password = "<API Key>"
          }
        }
        labels = {
          cluster = "minikube",
        }
      }

      otelcol.receiver.otlp "default" {
        grpc { endpoint = "0.0.0.0:4317" }
        http { endpoint = "0.0.0.0:4318" }
      }

      otelcol.processor.batch "default" {
        send_batch_size = 1000
        timeout = "10s"
      }

      otelcol.exporter.otlp "grafana_cloud" {
        endpoint = "tempo-prod-20-prod-ap-northeast-0.grafana.net:443"
        tls { insecure_skip_verify = true }
        headers = {
          "Authorization" = "Bearer <API Key>",
        }
      }

      otelcol {
        receivers  = [otelcol.receiver.otlp.default]
        exporters  = [otelcol.exporter.otlp.grafana_cloud]
        processors = [otelcol.processor.batch.default]
      }

  mounts:
    varlog: true
    
controller:
  tolerations:
    - key: "service"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "type"
      operator: "Exists"
      effect: "NoSchedule"