cluster:
  name: minikube

externalServices:
  prometheus:
    host: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net
    basicAuth:
      username: "2492573"
      password: "${GRAFANA_CLOUD_TOKEN}"
  loki:
    host: https://logs-prod-020.grafana.net
    basicAuth:
      username: "1241963"
      password: "${GRAFANA_CLOUD_TOKEN}"
  tempo:
    host: https://tempo-prod-14-prod-ap-southeast-1.grafana.net:443
    basicAuth:
      username: "1236274"
      password: "${GRAFANA_CLOUD_TOKEN}"

metrics:
  enabled: true
  alloy:
    metricsTuning:
      useIntegrationAllowList: true
  cost:
    enabled: true
  kepler:
    enabled: true
  node-exporter:
    enabled: true

logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true

traces:
  enabled: true

receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: false
  grafanaCloudMetrics:
    enabled: false

opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: minikube
    prometheus:
      external:
        url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-operator-crds:
  enabled: true

kepler:
  enabled: true

alloy: {}
alloy-events: {}
alloy-logs: {}
