apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Wizlit-Org/msa-logging.git
        revision: main
        directories:
          - path: argocd_apps/in-cluster
  template:
    metadata:
      name: '{{path.basename}}-infra'
    spec:
      project: default
      source:
        repoURL: https://github.com/Wizlit-Org/msa-logging.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
