apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
type: Opaque
data:
  admin-user: YWRtaW4=         # admin (base64)
  admin-password: YWRtaW5wYXNzd29yZA== # adminpassword (base64)