dex:
  enabled: false

notifications:
  enabled: true

configs:
  rbac:
    create: true
    policy.default: role:admin
    policy.csv: |
      p, role:admin, *, *, *, allow
      g, admin, role:admin

  secret:
    createSecret: true
    argocdServerAdminPassword: "$2b$12$VKegf7v84HeJd7skPX/rReZ6z1SW9XQqXZ2Kkzj8Ntkb7La8NYbOm"

applicationSet:
  enabled: true

redis:
  persistence:
    enabled: true
    storageClass: standard
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: argocd.43.202.138.109.nip.io
        paths:
          - path: /
            pathType: Prefix

  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

controller:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

repoServer:
  persistence:
    enabled: true
    storageClass: standard
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi